# Generated by Django 3.0.8 on 2020-08-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('requirements', models.TextField(verbose_name='Requerimientos')),
            ],
            options={
                'verbose_name': 'Oportunidad Laboral',
                'verbose_name_plural': 'Oportunidades Laborales',
            },
        ),
    ]
