# Generated by Django 3.0.12 on 2021-03-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_careers_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctacte',
            name='cta_cte',
            field=models.CharField(max_length=80, verbose_name='Tipo Cta. Cte.'),
        ),
    ]
