# Generated by Django 3.0.12 on 2021-09-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210917_1506'),
        ('website', '0004_auto_20210318_1728'),
    ]

    operations = [
    ]
