# Generated by Django 3.0.12 on 2021-09-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_incomequality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomequality',
            name='quality_datetime',
            field=models.DateTimeField(null=True, verbose_name='Fecha y Hora de Calidad'),
        ),
    ]
