# Generated by Django 3.0.12 on 2021-11-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210920_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='external_voucher_number',
            field=models.BigIntegerField(verbose_name='Numero Comprobante Externo'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='external_voucher_number',
            field=models.BigIntegerField(verbose_name='Numero Comprobante Externo'),
        ),
    ]
