# Generated by Django 3.0.12 on 2023-08-31 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20211109_1012'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='IncomeQuality',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='IncomeQuality',
                    table='extranet_incomequality',
                ),
            ],
        )
    ]
