# Generated by Django 3.0.12 on 2023-09-13 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_delete_incomequality'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Deliveries',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Deliveries',
                    table='extranet_deliveries',
                ),
            ],
        )
    ]
