# Generated by Django 3.0.12 on 2023-09-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_delete_sales'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='SpeciesHarvest',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='SpeciesHarvest',
                    table='extranet_speciesharvest',
                ),
            ],
        )
    ]
