# Generated by Django 3.0.12 on 2023-09-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_delete_speciesharvest'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Applied',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Applied',
                    table='extranet_applied',
                ),
            ],
        )
    ]
