# Generated by Django 3.0.12 on 2023-09-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_delete_applied'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='CtaCte',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='CtaCte',
                    table='extranet_ctacte',
                ),
            ],
        )
    ]
