# Generated by Django 3.0.12 on 2023-09-13 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_delete_ctacte'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='TicketsAnalysis',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='TicketsAnalysis',
                    table='extranet_ticketsanalysis',
                ),
            ],
        )
    ]
