# Generated by Django 3.0.12 on 2023-09-13 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_delete_ticketsanalysis'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='UserInfo',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='UserInfo',
                    table='extranet_userinfo',
                ),
            ],
        )
    ]
