# Generated by Django 3.0.12 on 2023-09-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_delete_userinfo'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='viewednotifications',
                    name='notification',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='viewednotifications',
                    name='user',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Notifications',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Notifications',
                    table='extranet_notifications',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='ViewedNotifications',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='ViewedNotifications',
                    table='extranet_viewednotifications',
                ),
            ],
        )
    ]
