# Generated by Django 3.0.12 on 2023-09-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20230913_0113'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='AccessLog',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='AccessLog',
                    table='extranet_accesslog',
                ),
            ],
        ),
    ]
