# Generated by Django 3.0.12 on 2023-09-13 23:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_delete_accesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='careers',
            name='requirements',
            field=tinymce.models.HTMLField(verbose_name='Requerimientos'),
        ),
    ]
