# Generated by Django 3.0.12 on 2023-09-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extranet', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Deliveries',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('algoritmo_code', models.IntegerField(verbose_name='Cuenta Algoritmo')),
                        ('name', models.CharField(max_length=150, verbose_name='Razón Social')),
                        ('indicator', models.CharField(max_length=1, verbose_name='Indicador')),
                        ('species', models.CharField(max_length=4, verbose_name='Especie')),
                        ('harvest', models.CharField(max_length=4, verbose_name='Cosecha')),
                        ('speciesharvest', models.CharField(max_length=8, null=True, verbose_name='Especie Cosecha')),
                        ('species_description', models.CharField(max_length=50, verbose_name='Especie y Cosecha')),
                        ('field', models.IntegerField(verbose_name='Codigo de Campo')),
                        ('field_description', models.CharField(max_length=100, verbose_name='Nombre de Campo')),
                        ('date', models.DateField(null=True, verbose_name='Fecha')),
                        ('voucher', models.CharField(max_length=16, verbose_name='Comprobante')),
                        ('gross_kg', models.IntegerField(verbose_name='Peso Bruto')),
                        ('humidity_percentage', models.FloatField(verbose_name='Humedad (%)')),
                        ('humidity_reduction', models.FloatField(verbose_name='Merma de Humedad')),
                        ('humidity_kg', models.IntegerField(verbose_name='Kilos de Humedad')),
                        ('shaking_reduction', models.FloatField(verbose_name='Merma de Zarandeo')),
                        ('shaking_kg', models.IntegerField(verbose_name='Kilos de Zarandeo')),
                        ('volatile_reduction', models.FloatField(verbose_name='Merma Volatil')),
                        ('volatile_kg', models.IntegerField(verbose_name='Kilos Volatil')),
                        ('price_per_yard', models.FloatField(verbose_name='Precio por Quintal')),
                        ('driver_code', models.IntegerField(verbose_name='Chofer')),
                        ('driver_name', models.CharField(max_length=150, verbose_name='Nombre del Chofer')),
                        ('factor', models.FloatField(verbose_name='Factor')),
                        ('grade', models.IntegerField(verbose_name='Grado')),
                        ('gluten', models.IntegerField(verbose_name='Gluten')),
                        ('number_1116A', models.IntegerField(verbose_name='Numero 1116A')),
                        ('km', models.IntegerField(verbose_name='Kilometros')),
                        ('external_voucher_number', models.BigIntegerField(verbose_name='Numero Comprobante Externo')),
                        ('service_billing_number', models.IntegerField(verbose_name='Numero Factura de Servicios')),
                        ('service_billing_date', models.DateField(null=True, verbose_name='Fecha Factura de Servicios')),
                        ('service_billing', models.CharField(max_length=50, verbose_name='Factura de Servicios')),
                        ('to_date', models.DateField(null=True, verbose_name='Fecha Entrega Hasta')),
                        ('observations', models.CharField(max_length=300, verbose_name='Observaciones')),
                        ('follow_destination', models.CharField(max_length=2, verbose_name='Sigue a Destino')),
                        ('net_weight', models.IntegerField(verbose_name='Peso Neto')),
                        ('tare', models.IntegerField(verbose_name='Tara')),
                    ],
                    options={
                        'verbose_name': 'Entregas',
                    },
                ),
            ],
            # Table already exists. See website/migrations/0010_delete_deliveries.py
            database_operations=[],
        ),
        migrations.AlterModelOptions(
            name='incomequality',
            options={'verbose_name': 'Calidad de Ingresos'},
        ),
    ]
