# Generated by Django 3.0.12 on 2023-09-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extranet', '0003_sales'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SpeciesHarvest',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('algoritmo_code', models.IntegerField(verbose_name='Cuenta Algoritmo')),
                        ('movement_type', models.CharField(max_length=1, verbose_name='Tipo Movimiento')),
                        ('species', models.CharField(max_length=4, verbose_name='Especie')),
                        ('harvest', models.CharField(max_length=4, verbose_name='Cosecha')),
                        ('speciesharvest', models.CharField(max_length=8, null=True, verbose_name='Especie Cosecha')),
                        ('species_description', models.CharField(max_length=50, verbose_name='Especie y Cosecha')),
                    ],
                    options={
                        'verbose_name': 'Especies y Cosechas',
                    },
                ),
            ],
            # Table already exists. See website/migrations/0012_delete_speciesharvest.py
            database_operations=[],
        ),
    ]
