# Generated by Django 3.0.12 on 2023-09-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extranet', '0006_ctacte'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='TicketsAnalysis',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('algoritmo_code', models.IntegerField(verbose_name='Cuenta Algoritmo')),
                        ('ticket', models.CharField(max_length=16, verbose_name='Ticket')),
                        ('field', models.IntegerField(verbose_name='Campo')),
                        ('field_description', models.CharField(max_length=100, verbose_name='Nombre de Campo')),
                        ('species', models.CharField(max_length=4, verbose_name='Especie')),
                        ('harvest', models.CharField(max_length=4, verbose_name='Cosecha')),
                        ('speciesharvest', models.CharField(max_length=8, null=True, verbose_name='Especie Cosecha')),
                        ('grade', models.IntegerField(verbose_name='Grado')),
                        ('factor', models.FloatField(verbose_name='Factor')),
                        ('analysis_costs', models.FloatField(verbose_name='Gastos de Analisis')),
                        ('gluten', models.IntegerField(verbose_name='Gluten')),
                        ('analysis_item', models.IntegerField(verbose_name='Rubro de Analisis')),
                        ('percentage', models.FloatField(verbose_name='Porcentaje')),
                        ('bonus', models.FloatField(verbose_name='Bonificacion')),
                        ('reduction', models.FloatField(verbose_name='Rebaja')),
                        ('item_descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                    ],
                    options={
                        'verbose_name': 'Analisis por Ticket',
                    },
                ),
            ],
            # Table already exists. See website/migrations/0015_delete_ticketanalysis.py
            database_operations=[],
        ),
    ]
