# Generated by Django 3.0.12 on 2023-09-13 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extranet', '0007_ticketsanalysis'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='UserInfo',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('algoritmo_code', models.IntegerField(unique=True, verbose_name='Cuenta Algoritmo')),
                        ('company_name', models.CharField(max_length=150, verbose_name='Razón Social')),
                        ('is_commercial', models.BooleanField(default=False, verbose_name='Es Comercial?')),
                        ('account_confirmed', models.BooleanField(default=False, verbose_name='Cuenta Confirmada?')),
                        ('random_password', models.BooleanField(default=True, verbose_name='Password Aleatorio')),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Usuario',
                        'verbose_name_plural': 'Usuarios',
                    },
                ),
            ],
            # Table already exists. See website/migrations/0016_delete_userinfo.py
            database_operations=[],
        ),
    ]
