# Generated by Django 3.0.12 on 2023-09-13 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extranet', '0009_notifications_viewednotifications'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AccessLog',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('algoritmo_code', models.IntegerField(verbose_name='Cuenta Algoritmo')),
                        ('logged', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora de Ingreso')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Log de Acceso',
                        'verbose_name_plural': 'Log de Acceso',
                    },
                ),
            ],
            # Table already exists. See website/migrations/0018_delete_accesslog.py
            database_operations=[],
        ),
    ]
