# Generated by Django 4.2.5 on 2023-09-16 21:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('extranet', '0010_accesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification',
            field=tinymce.models.HTMLField(verbose_name='Notificación'),
        ),
    ]
