# Generated by Django 4.2.5 on 2023-09-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extranet', '0011_alter_notifications_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewednotifications',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name='Fecha/Hora de visualización'),
        ),
    ]
