# Generated by Django 4.2.5 on 2023-09-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extranet', '0012_viewednotifications_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='affected_balance',
            field=models.CharField(default='', max_length=10, verbose_name='Saldo a Afectar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applied',
            name='affected_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Afectación'),
        ),
        migrations.AddField(
            model_name='applied',
            name='affected_voucher',
            field=models.CharField(max_length=16, null=True, verbose_name='Comprobante Afectado'),
        ),
        migrations.AddField(
            model_name='applied',
            name='amount_dolar',
            field=models.FloatField(default=0.0, verbose_name='Importe del Comprobante en Dólar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applied',
            name='amount_pesos',
            field=models.FloatField(default=0.0, verbose_name='Importe del Comprobante en Pesos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applied',
            name='link',
            field=models.CharField(max_length=120, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='ctacte',
            name='adjust_exchange_rate',
            field=models.FloatField(default=0.0, verbose_name='Tipo de Cambio Ajuste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctacte',
            name='affected_balance',
            field=models.CharField(default='', max_length=10, verbose_name='Saldo a Afectar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctacte',
            name='amount_dolar',
            field=models.FloatField(default=0.0, verbose_name='Importe del Comprobante en Dólar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctacte',
            name='amount_pesos',
            field=models.FloatField(default=0.0, verbose_name='Importe del Comprobante en Pesos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctacte',
            name='initial_balance_pesos',
            field=models.FloatField(default=0.0, verbose_name='Saldo Inicial Pesos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctacte',
            name='initial_balance_usd',
            field=models.FloatField(default=0.0, verbose_name='Saldo Inicial Dólar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctacte',
            name='link',
            field=models.CharField(max_length=120, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='applied',
            name='algoritmo_code',
            field=models.IntegerField(db_index=True, verbose_name='Cuenta Algoritmo'),
        ),
        migrations.AlterField(
            model_name='applied',
            name='expiration_date',
            field=models.DateField(db_index=True, null=True, verbose_name='Fecha Vencimiento'),
        ),
        migrations.AlterField(
            model_name='applied',
            name='issue_date',
            field=models.DateField(db_index=True, null=True, verbose_name='Fecha Emision'),
        ),
        migrations.AlterField(
            model_name='ctacte',
            name='algoritmo_code',
            field=models.IntegerField(db_index=True, verbose_name='Cuenta Algoritmo'),
        ),
        migrations.AlterField(
            model_name='ctacte',
            name='date_1',
            field=models.DateField(db_index=True, null=True, verbose_name='Fecha Vencimiento'),
        ),
        migrations.AlterField(
            model_name='ctacte',
            name='date_2',
            field=models.DateField(db_index=True, null=True, verbose_name='Fecha Emisión'),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='algoritmo_code',
            field=models.IntegerField(db_index=True, verbose_name='Cuenta Algoritmo'),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='indicator',
            field=models.CharField(max_length=6, verbose_name='Indicador'),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='speciesharvest',
            field=models.CharField(db_index=True, max_length=8, null=True, verbose_name='Especie Cosecha'),
        ),
        migrations.AlterField(
            model_name='incomequality',
            name='algoritmo_code',
            field=models.IntegerField(db_index=True, verbose_name='Cuenta Algoritmo'),
        ),
        migrations.AlterField(
            model_name='incomequality',
            name='speciesharvest',
            field=models.CharField(db_index=True, max_length=8, null=True, verbose_name='Especie Cosecha'),
        ),
        migrations.AlterField(
            model_name='incomequality',
            name='ticket',
            field=models.CharField(db_index=True, max_length=16, verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='algoritmo_code',
            field=models.IntegerField(db_index=True, verbose_name='Cuenta Algoritmo'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='indicator',
            field=models.CharField(max_length=6, verbose_name='Indicador'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='speciesharvest',
            field=models.CharField(db_index=True, max_length=8, null=True, verbose_name='Especie Cosecha'),
        ),
    ]
